### ISSUE TITLE
what the homepage has to say

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/facebook.tracking.exposed#1]
## What's the slogan on top?

We fight for a web that is home for the many, not propriety of the few.
We believe in a free and diverse internet as the foundation for a better tomorrow

## Which are the first three boxes?
- what we mean by display the algorithm
- what happen if you use this
- ethics and data-reuse

**Comment by privatemaker** [comment]
As discussed and now implemented these links are:

- **Reality Check** - for "what we mean by display the algorithm"
- **Zuckless News** - for "what happen if you use this"
- **Analysis & Publications** - for "ethics and data-reuse"

These three highlight are also in the topbar along with 

- **More** - for all the other pages and sections
