### ISSUE TITLE
need data for user profile (name and username)

### ISSUE THREAD

**Issue by privatemaker** [tracking-exposed/facebook.tracking.exposed#14]
in Reality Check interface of #7 there is placeholder text `Alice B. Carol` this was meant to be replaced with data from a user account so they clearly understand this was data harvested from when they are logged in / look at Facebook.

i am not sure best way to get this data at the moment. i can get from one of the items in `/api/v2/personal/tokentoken/enrich/2019-09-16` data with `item.user` which has value like `okra-ravioli-tapioca` or `asparagus-rhubarb-turnip`

my ideas was if user then has browser extension installed then it show their real name. what do you think @vecna ?

**Comment by vecna** [comment]
thanks for the analysis. At the moment we are not extracting the name/username of the person. I am not fond of looking for more data except the public posts. I suggest we keep using the pseudonym, and eventually, in the future, the fbtrexuser would decide their own name
