### ISSUE TITLE
after updating to 2.0.0 the plugin seems not tow work anymore

### ISSUE THREAD

**Issue by pstimpel** [tracking-exposed/facebook.tracking.exposed#22]
Using Firefox (uptodate) your extension isnot working anymore. It keeps telling me I should log into facebook. However, I am logged in.

I am running plugins to keep facebook sessions limited to a single tab (Multi Account Containers). However, this combination was working before very well. 

BR
Peter

**Comment by vecna** [comment]
Thanks for the feedback; in theory we should support the containers, but I confirm the bug:

![image](https://user-images.githubusercontent.com/89555/74112970-61273a00-4ba1-11ea-9078-b7a1ffe9cf10.png)

we'll look into it! thanks

**Comment by vecna** [comment]
today have been released the 2.1.2 version, it should work competely and also in firefox containers
