### ISSUE TITLE
add test data to repository

### ISSUE THREAD

**Issue by privatemaker** [tracking-exposed/facebook.tracking.exposed#3]
it would be helpful for front-end devlopers to have dump of the API data locally (so no need to mess around with CORS or local api server). Somethings like this is what I do locally:

```
static/testdata/reality-check/summary.json
static/testdata/zuckless-news/languages.json
```

this must obviously take into account privacy concerns

**Comment by vecna** [comment]
Ok. I've provided the summary (and also the stats, give it a look, it is the same of summary, but better organized. I think, in the future visualization, stats would be a better reference). 
the privacy concerns are managed by giving you the data from one of our dummy profiles who has zero friends and only follow mainstream newsmedia. all the informations presents can be considered "public and in the public interest".

**Comment by vecna** [comment]
tracking@testing:~/facebook.tracking.exposed$ ls -l fixtures/
    total 1452
    -rw-rw-r-- 1 tracking tracking     875 Jun  1 23:48 languages.json
    -rw-rw-r-- 1 tracking tracking 1197133 Jun  1 23:30 stats.json
    -rw-rw-r-- 1 tracking tracking  282595 Jun  1 23:31 summary.json
