### ISSUE TITLE
zuckless news not working 

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/facebook.tracking.exposed#5]
currently updated the https://testing.tracking.exposed, not working this:

![image](https://user-images.githubusercontent.com/89555/59159915-8e7e8e00-8ad0-11e9-84f4-1c2898b33c07.png)

**Comment by privatemaker** [comment]
oops. i make mistake here. I forgot to push the theme. please pull
hugo-theme-trex repo and re-build with that.

**Comment by vecna** [comment]
thanks, but I think a secondary issue comes because, to test the working flow, I've to redirect /api/v2 to the facebook.tracking.exposed server.

**Comment by privatemaker** [comment]
@vecna I am not sure what you are doing with the `api/v2` paths but yes it no longer exists or works. maybe open an issue so I understand and can plan as needed?

**Comment by vecna** [comment]
Ok, I checked, the server was apparently running. I've restarted and now comeback to work.

**Comment by vecna** [comment]
The first bug is the one addressed in the commit above. The API do not finish with '.json' when in production. Now, to be fixed, there is the composed path (it contains two slashes) 
![image](https://user-images.githubusercontent.com/89555/59453969-6618cb80-8e11-11e9-8193-1c6bf1397a7a.png)
