### ISSUE TITLE
Error in navbar resize

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/facebook.tracking.exposed#8]
When the browser is half size (I guess might happen also with certain mobile version) the navbar do not work well.

### before clicking:
![image](https://user-images.githubusercontent.com/89555/61044333-b6ffed80-a3d8-11e9-94ac-46b2d02d1d30.png)
### after clicking:
![image](https://user-images.githubusercontent.com/89555/61044354-c2531900-a3d8-11e9-8f6f-fd1abff752a7.png)

**Comment by privatemaker** [comment]
Recent changes by @lc-d and now myself with adding a `$icon-navbar-toggler-white` to the theme brings this up to the following fix. Is this ok?

![Screenshot_2019-07-21 Facebook Tracking Exposed](https://user-images.githubusercontent.com/49612519/61594564-86e0f780-abed-11e9-8858-3f9a656d3f6b.png)

![Screenshot_2019-07-21 Home Tracking Exposed](https://user-images.githubusercontent.com/49612519/61594565-87798e00-abed-11e9-807f-85469f001250.png)

![Screenshot_2019-07-21 YouTube Tracking Exposed](https://user-images.githubusercontent.com/49612519/61594566-87798e00-abed-11e9-92f1-7834ee5bf4fe.png)

**Comment by vecna** [comment]
thanks!
