### ISSUE TITLE
Site launch series of small tasks

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/facebook.tracking.exposed#9]
Dear @privatemaker this is the list of TODOs before the new style upgrade:

- [x] realitycheck picture
- [x] zuckless news picture
- [x] Analysis and publication picture
- [x] Fix scalability issue #8

**Comment by vecna** [comment]
And these are for my:

- [ ] import two content from the eu19 current design to the facebook one (infographic and data-activism)
- [x] review homepage
- [ ] review project page 
- [ ] review online slides 
- [ ] test realitycheck
- [ ] implement stats 
- [ ] implement realitycheck dummy token

**Comment by privatemaker** [comment]
Here is screenshot with icons for the Facebook apps

![Screenshot_2019-07-21 Facebook Tracking Exposed](https://user-images.githubusercontent.com/49612519/61594609-fd7df500-abed-11e9-8972-74162989354f.png)

The text above `We challenge Facebook ...` now is too long and cuts down on space, but that is separate issue that can be solved different ways.
